language: python
python: 3.7
env:
  - TOXENV=py37
  - TOXENV=py36
  - TOXENV=py35
  - TOXENV=py34
  - TOXENV=py33
  - TOXENV=py27
  - TOXENV=py26
  - TOXENV=style
  - TOXENV=docs
  - TOXENV=coveralls
  - TOXENV=extras-attrdict
  - TOXENV=extras-yaml
  - TOXENV=extras-none
  - TOXENV=pypy
  - TOXENV=pypy3
install: pip install tox
script: tox
